name = "PrettyTables"
uuid = "bf2635c2-15c2-11e9-0b27-5fb50ccc2906"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.1.0"
license = "MIT"
desc = "Print data in formatted tables"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
